export const bladeMaterial = [
    "Aluminium", 
    "Stainless Steel", 
    "Titanium", 
    "s32vn",
    "D2", 
    "s35vn", 
    "6061 Aluminium",
    "7075 Aluminium",
    "Plastic",
    "M390",
    "Elmax",
    "154CM",
    "14C28N",
    "MagnaCut",
    "Damascus",
    "AUS-10",
    "AEB-L",
    "12C27",
    "440C",
    "Other",
    "Unknown"
]